builds:
  - id: "ghrelnoty"
    main: ./cmd/ghrelnoty

    binary: ghrelnoty
    goos:
      - darwin
      - linux
      - windows

    goarch:
      - "386"
      - amd64
      - arm
      - arm64

    goarm:
      - "6"
      - "7"
