version: 2

builds:
  - id: "ghrelnoty"
    main: ./cmd/ghrelnoty

    binary: ghrelnoty
    goos:
      - darwin
      - linux
      - windows

    goarch:
      - "386"
      - amd64
      - arm
      - arm64

    goarm:
      - "6"
      - "7"

kos:
  - repositories:
      - ghcr.io/davquar/ghrelnoty
    tags:
      - "{{.Tag}}"
      - latest
    bare: true
    main: ./cmd/ghrelnoty
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64