log_level: debug
check_every: 3h
db_path: demo/.ghrelnoty.db
repositories:
  - name: firefly-iii/firefly-iii
    destination: email
destinations:
  email:
    type: smtp
    from: sample
    to: sample
    host: localhost
    port: 587
    username: demo
    password: demo