# log level: error, warning, info, debug
log_level: debug

# time between batches of requests.
check_every: 3h

# time between each request, mainly useful to avoid
# getting rate limited if requests are not authenticated
# and there are multiple repositories to check.
sleep_between: 2m

# path to store the database
db_path: /var/lib/ghrelnoty/ghrelnoty.db

# array of repositories to check
# format:
# - name: author/repo-name
#   destination: dest-name
repositories:
  - name: firefly-iii/firefly-iii
    type: github
    destination: email

# dictionary of destinations for notifications
# only one destination of type smtp is supported.
# name the destination as you wish (e.g., email).
destinations:
  email:
    type: smtp
    config:
      from: GHRelNoty <ghrelnoty@localhost>
      to: smtp4dev <test@localhost>
      host: localhost
      port: 2525
      username: demo
      password: demo
      html: true

metrics_port: 9090
