services:
  ghrelnoty:
    image: ghcr.io/davquar/ghrelnoty
    container_name: ghrelnoty
    restart: unless-stopped
    environment:
      GHRELNOTY_CONFIG_PATH: /etc/ghrelnoty/config.yaml
    ports:
      - "9090:9090"
    volumes:
      - "data:/var/lib/ghrelnoty"
      - "./config.yaml:/etc/ghrelnoty/config.yaml:ro"

volumes:
  data: