services:
  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: smtp4dev
    restart: always
    ports:
      - '127.0.0.1:5000:80'
      - '127.0.0.1:2525:25'
      - '127.0.0.1:1143:143'
    environment:
      - ServerOptions__Urls=http://*:80
      - ServerOptions__HostName=smtp4dev
