name: Go CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache-dependency-path: go.sum

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          problem-matchers: true
          args: --timeout 2m

      - name: Build
        run: go build -v ./cmd/...

      - name: Test
        run: go test -v ./...
